# Generated by Django 2.2.3 on 2019-07-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190721_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='<No title>', max_length=180),
        ),
    ]
