# Generated by Django 2.2.3 on 2019-07-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190721_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
